### ISSUE TITLE
Norminette not found on VS code

### ISSUE THREAD

**Issue by bmirlico** [Mariusmivw/vscode-42-norminette-3-highlighter#13]
![Norminette error](https://user-images.githubusercontent.com/74457287/207412033-17b4ad65-666c-4d44-81c0-65d3a1db89f3.PNG)

Hi!

Hope you are well :)
Just wanted to report an issue that I currently have on Norminette : it is not found by VSCode and therefore not working.
Perhaps, someone had the same issue before?
Thanks for the help!

Bastien

**Comment by Kumiihoo** [comment]
This could help you:

https://github.com/Mariusmivw/vscode-42-norminette-3-highlighter/issues/10#issuecomment-1431083554

**Comment by excaribur** [comment]
How to resolve this issue on the MacBook Pro ?

**Comment by SirMorfield** [comment]
This VScode extention does nothing more than run the command `norminette` in a shell, parses the output, and injects it in VSCode.
The error says that the extension can't execute `norminette`, so the executable does not exist or is not in your PATH.

If you insist on using windows, this will help: 
[#10](https://github.com/Mariusmivw/vscode-42-norminette-3-highlighter/issues/10#issuecomment-1431083554)
