### ISSUE TITLE
Norminette not found

### ISSUE THREAD

**Issue by Gillian-Delvigne** [Mariusmivw/vscode-42-norminette-3-highlighter#19]
Hi,

I've been working with VS Code on macOS Monterey (version 12.7.3) and the VS Code version I'm using is 1.87.2 (Universal). Recently, I've encountered an issue where I can't utilize the extension due to an error stating, "Norminette not found [link to the Norminette GitHub repo]". I've ensured that my Norminette version is up-to-date (3.3.55), installed with its default settings. Although I've attempted to update it, and it operates correctly when executing the "norminette" command directly, the error persists within VS Code. My Python and pip installations are also current, with versions 3.11.7 and 24.0, respectively, located at /usr/local/lib/python3.11/site-packages/pip (python 3.11).

I'm at a loss for what might be causing this issue. Do you have any suggestions?

Thank you for your assistance.

**Comment by Mariusmivw** [comment]
You could try to set `codam-norminette-3.command` to `python3 -m norminette`, or if that doesn't work try to set it to the actual path of norminette (You can get it by running `where norminette` in a terminal)

**Comment by Gillian-Delvigne** [comment]
Thank you for your quick reply.
I changed this in my settings.json `"codam-norminette-3.command": "python3 -m norminette`", and it worked perfectly.
Thanks.
