### ISSUE TITLE
Norminette Highlighter on VSCode - Windows 10

### ISSUE THREAD

**Issue by Nazza01** [Mariusmivw/vscode-42-norminette-3-highlighter#4]
Hi,
I have downloaded and used the norminette highlighter extension on a Mac which works completely fine.
When I download the extension through the VSCode Marketplace, Extensions tab or OpenVSX Marketplace the extension comes up with an error:
![vscoderror](https://user-images.githubusercontent.com/9160772/128499203-94979f1b-a699-4b8d-a346-2887e788421e.JPG)
 
 Let me know if you need any more information as I would like to get it working when I move to a Windows environment, it's not essential but would be nice.
 Thanks!

**Comment by fletcher97** [comment]
I have the same problem. I'm using this with Remote-WSL extention and code-insider. I have norminette installed on wsl and I get the exact same message. Norminette works fine on the terminal. If you need more info let me know.
